### ISSUE TITLE
Нет возможности преобразовывать строку в html

### ISSUE THREAD

**Issue by LEONeso** [kwolfy/KEmoji#6]
Просмотрел весь код и документацию, нет возможности передачи строки и получения html кода.

Как возможно это реализовать?

Допустим я получаю ajax массив, и хочу спарсить строку, чтоб потом вставить сообщение со смайлами, а не кодами.

**Comment by LEONeso** [comment]
Делаю так: obj.message.replace(/\$#(.*?)#\$/g, '<img src="/images/opacity.png" onresizestart="return false" class="ke ke-$1">'),

**Comment by kwolfy** [comment]
Как это нет?
<code>
emoji.setValue('Hello $#D83DDE10#$') // задаем значение ввиде текста
</code>
